#!/usr/bin/env python3
"""Generate a stress-test SystemRDL file.

Default: 1000 registers × 30 fields each (committed as stress_1000.rdl).
Override via CLI for bigger fixtures (not committed; .gitignored).

  # Default 1k:
  python3 examples/gen_stress.py > examples/stress_1000.rdl

  # 100k regs (100 regfiles × 1000 regs):
  python3 examples/gen_stress.py --regfiles 100 --regs-per-file 1000 \\
      -o examples/stress_100k.rdl

Layout:

  - One ``stress_reg_t`` definition with N single-bit fields (default 30).
    Each register weighs 32 bits — trailing bits stay unused.
  - K regfiles × M registers each. Tests both flat scrolling (within a
    regfile) and tree depth (K collapsible containers).
  - Single addrmap ``stress_top``.
"""

from __future__ import annotations

import argparse
import sys


def emit(regfiles: int, regs_per_file: int, fields_per_reg: int,
         reg_stride: int = 4, bank_stride: int | None = None) -> str:
    if bank_stride is None:
        # Pick a power-of-two bank stride large enough to hold all regs in a bank,
        # with at least 25% headroom for visual breathing room.
        min_bank_size = regs_per_file * reg_stride
        bank_stride = 1
        while bank_stride < min_bank_size * 5 // 4:
            bank_stride <<= 1

    total_regs = regfiles * regs_per_file
    total_fields = total_regs * fields_per_reg

    lines: list[str] = []
    add = lines.append

    add("// Auto-generated by examples/gen_stress.py — do not edit by hand.")
    add(f"// Layout: {regfiles} regfiles × {regs_per_file} regs × {fields_per_reg} fields = "
        f"{total_regs} regs / {total_fields} fields total.")
    add("")
    add("reg stress_reg_t {")
    add('    name = "Stress test register";')
    add(f'    desc = "{fields_per_reg} single-bit flags.";')
    for i in range(fields_per_reg):
        add(f'    field {{ sw=rw; hw=r; desc="Flag {i:02d}."; }} f{i:02d}[{i}:{i}] = 0;')
    add("};")
    add("")
    # Width of regfile/reg index for zero-padding (3 → 4 → 5 digits)
    rf_width = max(2, len(str(regfiles - 1)))
    rg_width = max(3, len(str(regs_per_file - 1)))
    addr_hex_width = max(4, len(f"{regs_per_file * reg_stride - 1:X}"))

    for rf in range(regfiles):
        add(f"regfile bank_{rf:0{rf_width}d}_t {{")
        add(f'    name = "Bank {rf:0{rf_width}d}";')
        add(f'    desc = "Bank {rf:0{rf_width}d}: {regs_per_file} registers.";')
        for r in range(regs_per_file):
            offset = r * reg_stride
            add(f"    stress_reg_t REG_{r:0{rg_width}d} @ 0x{offset:0{addr_hex_width}X};")
        add("};")
        add("")
    add("addrmap stress_top {")
    add(f'    name = "Stress: {total_regs} registers × {fields_per_reg} fields";')
    add('    desc = "Generated stress fixture for the SystemRDL viewer.";')
    bank_addr_hex_width = max(4, len(f"{(regfiles - 1) * bank_stride:X}"))
    for rf in range(regfiles):
        add(f"    bank_{rf:0{rf_width}d}_t bank_{rf:0{rf_width}d} "
            f"@ 0x{rf * bank_stride:0{bank_addr_hex_width}X};")
    add("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regfiles", type=int, default=10,
                    help="Number of regfiles / banks (default: 10)")
    ap.add_argument("--regs-per-file", type=int, default=100,
                    help="Registers per regfile (default: 100)")
    ap.add_argument("--fields-per-reg", type=int, default=30,
                    help="Single-bit fields per register (default: 30, max: 32)")
    ap.add_argument("-o", "--out", type=str, default="-",
                    help="Output path (default: stdout)")
    args = ap.parse_args()

    if args.fields_per_reg > 32:
        ap.error("--fields-per-reg must be <= 32 (single 32-bit register)")

    text = emit(args.regfiles, args.regs_per_file, args.fields_per_reg)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        with open(args.out, "w") as f:
            f.write(text)
        print(f"wrote {args.out}: "
              f"{args.regfiles * args.regs_per_file} regs, "
              f"{len(text):,} bytes",
              file=sys.stderr)


if __name__ == "__main__":
    main()
