#!/usr/bin/env python3
"""Generate a stress-test SystemRDL file: 1000 registers × 30 fields each.

  python3 examples/gen_stress.py > examples/stress_1000.rdl

Layout:

  - One ``stress_reg_t`` definition with 30 single-bit fields (f00..f29).
    Each register weighs 32 bits — the trailing 2 bits stay unused.
  - 10 regfiles, 100 registers each. Tests both flat scrolling (within a
    regfile) and tree depth (10 collapsible containers).
  - Single addrmap ``stress_top``. Total span: 0x4000 (16 KB).
"""

from __future__ import annotations

import sys

REGS_PER_FILE = 100
REGFILES = 10
FIELDS_PER_REG = 30
REG_STRIDE = 4  # 32-bit regs, byte-addressed


def emit() -> str:
    lines: list[str] = []
    add = lines.append

    add("// Auto-generated by examples/gen_stress.py — do not edit by hand.")
    add(f"// Layout: {REGFILES} regfiles × {REGS_PER_FILE} regs × {FIELDS_PER_REG} fields = "
        f"{REGFILES * REGS_PER_FILE} regs / {REGFILES * REGS_PER_FILE * FIELDS_PER_REG} fields total.")
    add("")
    add("reg stress_reg_t {")
    add('    name = "Stress test register";')
    add('    desc = "30 single-bit flags. Bits 30 and 31 are reserved.";')
    for i in range(FIELDS_PER_REG):
        add(f'    field {{ sw=rw; hw=r; desc="Flag {i:02d}."; }} f{i:02d}[{i}:{i}] = 0;')
    add("};")
    add("")
    for rf in range(REGFILES):
        add(f"regfile bank_{rf:02d}_t {{")
        add(f'    name = "Bank {rf:02d}";')
        add(f'    desc = "Bank {rf:02d}: {REGS_PER_FILE} registers.";')
        for r in range(REGS_PER_FILE):
            offset = r * REG_STRIDE
            add(f"    stress_reg_t REG_{r:03d} @ 0x{offset:04X};")
        add("};")
        add("")
    add("addrmap stress_top {")
    add('    name = "Stress: 1000 registers × 30 fields";')
    add('    desc = "Generated stress fixture for the SystemRDL viewer.";')
    bank_size = REGS_PER_FILE * REG_STRIDE  # 0x190 = 400 bytes
    bank_stride = 0x400  # 1KB per bank — gives us breathing room
    for rf in range(REGFILES):
        add(f"    bank_{rf:02d}_t bank_{rf:02d} @ 0x{rf * bank_stride:04X};")
    add("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.stdout.write(emit())
